#spring:
#  datasource:
#    url: jdbc:sqlserver://school.database.windows.net:1433;database=school
#    username: adminfahim
#    password: adminadmin1@
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
azure:
  function:
    base-url: https://azurefunctions-1766754802726.azurewebsites.net
    process-employee-path: /api/employees/process
    timeout-ms: 10000

spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://learningjava-kv.vault.azure.net/



  datasource:
    url: ${sqldburl}
#    username: ${sqldbusername}
#    password: ${sqldbpassword}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


