#spring:
#  datasource:
#    url: jdbc:sqlserver://school.database.windows.net:1433;database=school
#    username: adminfahim
#    password: adminadmin1@
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
azure:
  function:
    base-url: https://azurefunctions-1766754802726.azurewebsites.net
    process-employee-path: /api/employees/process
    timeout-ms: 10000
  storage:
    container-name: "profile-pictures"
    account-name: "4cbaee0be46d45bdbdcd"
app:
  oauth2:
    redirect-uri: http://localhost:3000/oauth-success
jwt:
  secret: ${learning-app-jwt-secret}
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "Ov23li9GAfRojGVdRape"
            client-secret: ${github-client-secret}
            scope:
              - read:user
              - user:email
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://learningjava-kv.vault.azure.net/
  datasource:
    url: jdbc:sqlserver://school.database.windows.net:1433;
      database=school;
      encrypt=true;
      trustServerCertificate=false;
      authentication=ActiveDirectoryDefault;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
