azure:
  function:
    base-url: https://azurefunctions-1766754802726.azurewebsites.net
    process-employee-path: /api/employees/process
    timeout-ms: 10000
  storage:
    container-name: "profile-pictures"
    account-name: "4cbaee0be46d45bdbdcd"
jwt:
  secret: ${learning-app-jwt-secret}
app:
  oauth2:
    redirect-uri: https://learningdev1s-hcb4h4c0hwcjb9ba.centralus-01.azurewebsites.net/oauth-success

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "Ov23li9GAfRojGVdRape"
            client-secret: ${github-client-secret}
            scope:
              - read:user
              - user:email
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://learningjava-kv.vault.azure.net/
    datasource:
      url: ${sqldburlauthentication}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
